### ISSUE TITLE
React & Redux group project: set up your Kanban board

### ISSUE THREAD

**Issue by Amazinggracee** [Amazinggracee/Redux-group-project#22]
### Kanban board setup
https://github.com/Amazinggracee/Redux-group-project/projects/1
For this project, there are only two people handling it 
Naledi Dikgale
Amarachi Dimkpa

**Comment by Olamarx** [comment]
> ### Kanban board setup
> https://github.com/Amazinggracee/Redux-group-project For this project, there are only two people handling it Naledi Dikgale Amarachi Dimkpa

Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does have a link but not to your kanban board project, kindly change it.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by adel-gu** [comment]
# Status: REQUIRED CHANGES ♻️ 
**Hi  @Naledi-Dikgale  & @Amazinggracee  👋🏼** 

Good job so far! 👏🏼👏🏼👏🏼 however, there are some issues that you still need to work on to go to the next project but you are almost there! 💪🏼💪🏼💪🏼. 

![](https://media1.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif?cid=ecf05e47gehzel12kjeptl427bdnj4gfo7gttvq5y7i4y9b6&rid=giphy.gif&ct=g)

## Highlights
- Provided link to the project ✔️ 
- Provided information about the number of people in their group ✔️ 
- Copied template board ✔️ 

## Required Changes ♻️
- [ ]  Please ensure that you remove all cards with the **[Team3]** prefix and after that, the total card number should be 17, currently your total card number is 17 and the board still contains cards with the **[Team3]** prefix!!.
- [ ]  Tasks should be distributed in a fairway, currently:
    - @Naledi-Dikgale has 10 cards and @Amazinggracee has 09.
    - @Naledi-Dikgale has 20 [Xpt] and @Amazinggracee has 13 [Xpt]
- [ ] Each student should have cards with all required categories `Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters`. Currently:
    - @Naledi-Dikgale has one extra `Fetch data` and @Amazinggracee has none.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
